# Mean Normalization

In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is *normalized* in order to work correctly. The idea of normalization, also known as *feature scaling*, is to ensure that all the data is on a similar scale, *i.e.* that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.

In this lab, you will be performing a different kind of feature scaling known as *mean normalization*. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform *mean normalization* your data will not only be scaled but it will also have an average of zero. 

# To Do:

You will start by importing NumPy and creating a rank 2 ndarray of random integers between 0 and 5,000 (inclusive) with 1000 rows and 20 columns. This array will simulate a dataset with a wide range of values. Fill in the code below

In [2]:
# import NumPy into Python
import numpy as np

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X =  np.random.randint(0,5001,size=(1000,20))

# print the shape of X
print(X)

[[3004 1200 2443 ... 4742 4398 4499]
 [1648 4172 2975 ... 3589 1942 2481]
 [4907   33 1203 ...  212  496  299]
 ...
 [3249  904 4347 ... 3169 2618 2741]
 [3203  371 2229 ... 1422 1909  712]
 [2399  411 4435 ... 1440 1326  401]]


Now that you created the array we will mean normalize it. We will perform mean normalization using the following equation:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. In other words, mean normalization is performed by subtracting from each column of $X$ the average of its values, and then by dividing by the standard deviation of its values. In the space below, you will first calculate the average and standard deviation of each column of $X$. 

In [3]:
# Average of the values in each column of X
ave_cols = X.mean(axis=0)

# Standard Deviation of the values in each column of X
std_cols = X.std(axis=0)

If you have done the above calculations correctly, then `ave_cols` and `std_cols`, should both be vectors with shape `(20,)` since $X$ has 20 columns. You can verify this by filling the code below:

In [4]:
# Print the shape of ave_cols
print(ave_cols)

# Print the shape of std_cols
print(std_cols)

[2527.817 2516.539 2453.076 2616.354 2489.822 2546.48  2460.484 2578.886
 2499.126 2404.758 2522.705 2444.179 2577.582 2408.304 2497.4   2526.773
 2504.508 2464.802 2451.978 2563.649]
[1472.85209832 1423.10159738 1400.50619928 1476.11224529 1418.20104792
 1443.25431771 1430.80705818 1421.56867122 1453.18261142 1448.6375259
 1453.63773891 1422.28679772 1462.309175   1397.76294828 1450.20624257
 1495.21766558 1473.1397184  1426.97989572 1425.14978073 1477.49396811]


You can now take advantage of Broadcasting to calculate the mean normalized version of $X$ in just one line of code using the equation above. Fill in the code below

In [5]:
# Mean normalize X
X_norm = (X[:, 0:] - ave_cols[:])/std_cols[:]

If you have performed the mean normalization correctly, then the average of all the elements in $X_{\tiny{\mbox{norm}}}$ should be close to zero, and they should be evenly distributed in some small interval around zero. You can verify this by filing the code below:

In [6]:
# Print the average of all the values of X_norm
print(X_norm)

# Print the average of the minimum value in each column of X_norm
print(X_norm.min(axis=0))

# Print the average of the maximum value in each column of X_norm
print(X_norm.max(axis=0))


[[ 0.32330673 -0.92511947 -0.00719454 ...  1.59581646  1.36548595
   1.30988758]
 [-0.59735597  1.16327675  0.37266811 ...  0.78781628 -0.35784169
  -0.05593864]
 [ 1.61535771 -1.74515931 -0.89258869 ... -1.57872021 -1.37247188
  -1.53276362]
 ...
 [ 0.48965066 -1.13311587  1.3523139  ...  0.49348838  0.11649442
   0.12003501]
 [ 0.45841874 -1.50764991 -0.15999644 ... -0.73077554 -0.38099715
  -1.25323625]
 [-0.08746092 -1.47954229  1.41514832 ... -0.71816148 -0.79007696
  -1.4637278 ]]
[-1.70948393 -1.76553733 -1.74870772 -1.76839804 -1.75491479 -1.75955129
 -1.71545422 -1.80637492 -1.71700788 -1.65587178 -1.73062719 -1.71426677
 -1.74968607 -1.71867769 -1.72072077 -1.68990312 -1.70011572 -1.72238026
 -1.71559371 -1.73377967]
[1.67782156 1.73526683 1.80714944 1.61142624 1.76715283 1.69098403
 1.77418471 1.70101807 1.71752262 1.78667331 1.7035159  1.78573056
 1.65451879 1.85202792 1.71534222 1.65208522 1.69399546 1.7759171
 1.77947752 1.64829844]


You should note that since $X$ was created using random integers, the above values will vary. 

# Data Separation

After the data has been mean normalized, it is customary in machine learnig to split our dataset into three sets:

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The dataset is usually divided such that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. 

In this part of the lab you will separate `X_norm` into a Training Set, Cross Validation Set, and a Test Set. Each data set will contain rows of `X_norm` chosen at random, making sure that we don't pick the same row twice. This will guarantee that all the rows of `X_norm` are chosen and randomly distributed among the three new sets.

You will start by creating a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this by using the `np.random.permutation()` function. The `np.random.permutation(N)` function creates a random permutation of integers from 0 to `N - 1`. Let's see an example:

In [7]:
# We create a random permutation of integers 0 to 4
np.random.permutation(5)

# To Do

In the space below create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this in one line of code by extracting the number of rows of `X_norm` using the `shape` attribute and then passing it to the  `np.random.permutation()` function. Remember the `shape` attribute returns a tuple with two numbers in the form `(rows,columns)`.

In [12]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row_indices = np.random.permutation(1000)

print(row_indices)

[ 55  51 543 120 528 831 727 459 697 809 397 814 179 500 372 381 504 626
 856 991 682 184  39 439 823 205 353  40 873 769 122 657 702 441  24 968
 333 972 464 993 418 787 926 407 614 535 843 921 402 974 832 235 681 323
 554 818 143 896 731  94 204 699 467 236  66 750 773  77 165 992 713 196
 836  23 609 639 957 948 562 346 364 250 443 748 945  88 107 796 105 976
 819 804 160 462 801 325 255 564 715 794 525  31 735 477 546 598 339 167
 784 686 350 724 815 181 211  91 338 349 398 109  14 351 401 133 555 502
 261 280 473 545 150 618 385 121 461 408 517 917 541 745 202 227 566 692
 332 284 198 847 982 729  90 696  89 757 137 849 446 786  70  64 740 802
 344 842 486 688 359 617 630 673  41   5 951 225 549 575 751 436 985 168
 734 180 298 474 149 886 723 986 303 714 203 521 505 793 108 677 741 694
 690 629 428 172 601  45 648 300 489 559 199 239 193 508 966 602 447  30
 707 206 479 301 118 855 520 961 188 563 537 619  60 613 483 324 157 365
 647 947 576 328 542 653 669 104 652 774  78 977 96

Now you can create the three datasets using the `row_indices` ndarray to select the rows that will go into each dataset. Rememeber that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. Each set requires just one line of code to create. Fill in the code below

In [17]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.
train_indices = row_indices[:600]
print("train_indices: \n", train_indices)
cross_val_indices = row_indices[600:800]
print("cross_val_indices: \n", cross_val_indices)
test_indices = row_indices[800:]
print("test_indices: \n", test_indices)

# Create a Training Set
X_train = X[train_indices,:]
print("X_train: \n", X_train)

# Create a Cross Validation Set
X_crossVal = X[cross_val_indices,:]
print("X_crossVal: \n", X_crossVal)

# Create a Test Set
X_test = X[test_indices,:]
print("X_test: \n", X_test)


train_indices: 
 [ 55  51 543 120 528 831 727 459 697 809 397 814 179 500 372 381 504 626
 856 991 682 184  39 439 823 205 353  40 873 769 122 657 702 441  24 968
 333 972 464 993 418 787 926 407 614 535 843 921 402 974 832 235 681 323
 554 818 143 896 731  94 204 699 467 236  66 750 773  77 165 992 713 196
 836  23 609 639 957 948 562 346 364 250 443 748 945  88 107 796 105 976
 819 804 160 462 801 325 255 564 715 794 525  31 735 477 546 598 339 167
 784 686 350 724 815 181 211  91 338 349 398 109  14 351 401 133 555 502
 261 280 473 545 150 618 385 121 461 408 517 917 541 745 202 227 566 692
 332 284 198 847 982 729  90 696  89 757 137 849 446 786  70  64 740 802
 344 842 486 688 359 617 630 673  41   5 951 225 549 575 751 436 985 168
 734 180 298 474 149 886 723 986 303 714 203 521 505 793 108 677 741 694
 690 629 428 172 601  45 648 300 489 559 199 239 193 508 966 602 447  30
 707 206 479 301 118 855 520 961 188 563 537 619  60 613 483 324 157 365
 647 947 576 328 542 653 669 104 6

If you performed the above calculations correctly, then `X_tain` should have 600 rows and 20 columns, `X_crossVal` should have 200 rows and 20 columns, and `X_test` should have 200 rows and 20 columns. You can verify this by filling the code below:

In [21]:
# Print the shape of X_train
print("X_train:\n", X_train, "\nShape: ", X_train.shape)

# Print the shape of X_crossVal
print("X_crossVal:\n", X_crossVal, "\nShape: ", X_crossVal.shape)

# Print the shape of X_test
print("X_test:\n", X_test, "\nShape: ", X_test.shape)


X_train:
 [[2187  238 3994 ... 3413 2777  384]
 [4111 4670 1518 ... 1060 1723 2520]
 [1469   22 3776 ... 2433 1860 3692]
 ...
 [1755  322 2012 ... 4042 2241 2340]
 [1918 3428 3059 ... 4146 4328  169]
 [4998 1343 2028 ... 3308 3439  451]] 
Shape:  (600, 20)
X_crossVal:
 [[2895 3412 4270 ... 4833 4973 2994]
 [3342 3763 1402 ...  475  864 2833]
 [4520 2560 2810 ...  802 1739 4361]
 ...
 [1286  720 3611 ... 3363 2619 3602]
 [4117 3041   27 ... 3252  716 4609]
 [3153 3630 4444 ... 1948 1301 1696]] 
Shape:  (200, 20)
X_test:
 [[4973 2961 3809 ... 1816 3282 2284]
 [3233 4856 2950 ... 2568 4000 4957]
 [1741 4473 3539 ... 4484 4819  133]
 ...
 [4718  101 3669 ... 4335 2680  541]
 [3890 3124  748 ... 3180  165 2558]
 [4152 1924 3644 ... 3416 4177 3098]] 
Shape:  (200, 20)
